### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by kankaristo** [atom-minimap/minimap#339]
Minimap started throwing this error yesterday. It seems to happen pretty much all the time: typing, moving the cursor, changing tabs, etc.

I updated to Atom 0.206.0, which by default disables all deprecated APIs. Also new in that version is a new "rendering strategy" and preview tabs (which I turned on).

```
TypeError: undefined is not a function
  at Decoration.module.exports.Decoration.setProperties (/usr/share/atom/resources/app.asar/src/decoration.js:135:28)
  at new Decoration (/usr/share/atom/resources/app.asar/src/decoration.js:58:12)
  at Minimap.module.exports.DecorationManagement.decorateMarker (/home/sami/.atom/packages/minimap/lib/mixins/decoration-management.coffee:203:22)
  at MinimapFindResultsView.markersUpdated (/home/sami/.atom/packages/minimap-find-and-replace/lib/minimap-find-results-view.coffee:28:30)
  at /home/sami/.atom/packages/minimap-find-and-replace/lib/minimap-find-results-view.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at BufferSearch.module.exports.BufferSearch.recreateMarkers (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:144:29)
  at BufferSearch.module.exports.BufferSearch.setEditor (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:62:19)
  at /usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find.js:46:36
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:298:21)
  at tabs-tab.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:171:24)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by kankaristo** [comment]
This could be caused by https://github.com/atom/settings-view/issues/527.

I was getting weird errors all over the place, but turning off "Use Preview Tabs" seems to fix them.

**Comment by abe33** [comment]
> This could be caused by atom/settings-view#527.

Nope, see #333 for the details, it's now fixed with 4.9.4.

Just to make sure I tried with the `Use Preview Tab` enabled and it works as expected :)

**Comment by kankaristo** [comment]
Ah, okay. The `settings-view` error came back too (restarting Atom fixed it temporarily), so probably nothing to do with preview tabs.

I went to settings and saw that I had 4.9.4 installed. Then I opened `minimap` settings and saw this:
![screenshot from 2015-06-05 15 47 29](https://cloud.githubusercontent.com/assets/3522333/8006280/07fa8784-0b9b-11e5-8d4b-de29d434bfac.png)

So I have 4.9.4 installed **and** 4.9.4 is available? :laughing:

**Comment by kankaristo** [comment]
I don't know what kind of twilight zone my Atom installation is in, but `minimap` is no longer throwing the error. :+1:

**Comment by abe33** [comment]
Glad to hear that, I'm not sure why the settings view tells you that there's a new version though.

**Comment by abe33** [comment]
Sorry, got the issue number wrong, it was #335 and not #333 (I edited my previous answer too).

**Comment by pohmelie** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Ubuntu 14.04.2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.9.4


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app.asar/src/decoration.js:135

TypeError: undefined is not a function
  at Decoration.module.exports.Decoration.setProperties (/usr/share/atom/resources/app.asar/src/decoration.js:135:28)
  at new Decoration (/usr/share/atom/resources/app.asar/src/decoration.js:58:12)
  at Minimap.module.exports.DecorationManagement.decorateMarker (/home/poh/.atom/packages/minimap/lib/mixins/decoration-management.coffee:203:22)
  at FakeEditor.(anonymous function) [as decorateMarker] (/home/poh/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:25:30)
  at /home/poh/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:73:31
  at TextBuffer.module.exports.TextBuffer.scanInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:837:9)
  at TextEditor.module.exports.TextEditor.scanInBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:2079:26)
  at FakeEditor.(anonymous function) [as scanInBufferRange] (/home/poh/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:18:30)
  at MinimapHighlightSelectedView.handleSelection (/home/poh/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:68:14)
  at MinimapHighlightSelectedView.handleSelection (/home/poh/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
  at /home/poh/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:93:12
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.selectionRangeChanged (/usr/share/atom/resources/app.asar/src/text-editor.js:2066:27)
  at Selection.module.exports.Selection.screenRangeChanged (/usr/share/atom/resources/app.asar/src/selection.js:877:26)
  at /usr/share/atom/resources/app.asar/src/selection.js:43:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/usr/share/atom/resources/app.asar/src/marker.js:270:27)
  at /usr/share/atom/resources/app.asar/src/marker.js:65:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:400:20)
  at Marker.module.exports.Marker.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:345:12)
  at Marker.module.exports.Marker.setRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:108:19)
  at Marker.module.exports.Marker.setBufferRange (/usr/share/atom/resources/app.asar/src/marker.js:137:32)
  at /usr/share/atom/resources/app.asar/src/selection.js:117:24
  at Selection.module.exports.Selection.modifySelection (/usr/share/atom/resources/app.asar/src/selection.js:906:7)
  at Selection.module.exports.Selection.setBufferRange (/usr/share/atom/resources/app.asar/src/selection.js:110:19)
  at Selection.module.exports.Selection.selectWord (/usr/share/atom/resources/app.asar/src/selection.js:386:12)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/usr/share/atom/resources/app.asar/src/text-editor-component.js:552:42)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
     -9:46.2.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -9:45.3.0 core:save (atom-text-editor.editor.is-focused)
     -9:40.4.0 core:close (atom-text-editor.editor.is-focused)
     -9:39.9.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -8:34.9.0 application:new-file (atom-pane.pane.active)
  2x -8:33.7.0 core:save (atom-text-editor.editor.is-focused)
     -8:24.9.0 run-in-terminal:start-terminal-here (atom-text-editor.editor.is-focused)
  2x -2:29.7.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -2:28.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:57.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:34.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "projectHome": "/home/poh/pro",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "minimap": {
    "plugins": {
      "highlight-selected": true
    },
    "displayPluginsControls": false
  }
}
```

### Installed Packages

```coffee
# User
highlight-line, v0.10.2
highlight-selected, v0.9.3
language-lua, v0.9.3
linter, v0.12.7
linter-pep8, v0.2.0
minimap, v4.9.4
minimap-highlight-selected, v4.3.0
run-in-terminal, v0.2.2

# Dev
No dev packages
```

Same issue, but it looks like it is minimap-highlight-selected issue.
https://github.com/atom-minimap/minimap-highlight-selected/issues/11

**Comment by abe33** [comment]
The issue was related to the decoration API, so potentially all packages that make use of that API can trigger this error. However it was fixed in v4.9.4, have you try to restart Atom?

**Comment by pohmelie** [comment]
Oh, my bad, I forgot about restart after update. :grimacing:
