### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScreenHeightAndWidth' of null

### ISSUE THREAD

**Issue by pgurusinga** [atom-minimap/minimap#373]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.1
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setScreenHeightAndWidth' of null

```
At /Users/pramgurusinga/.atom/packages/minimap/lib/minimap-element.coffee:419

TypeError: Cannot read property 'setScreenHeightAndWidth' of null
  at atom-text-editor-minimap.MinimapElement.measureHeightAndWidth (/Users/pramgurusinga/.atom/packages/minimap/lib/minimap-element.coffee:419:13)
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/Users/pramgurusinga/.atom/packages/minimap/lib/minimap-element.coffee:91:6)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:150:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:242:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:306:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  2x -1:42.5.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
     -1:36.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:33.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:29.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:26.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:05.5.0 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.10.1
linter, v1.4.3
minimap, v4.13.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Thanks for the report, I just published a patch for this issue.

**Comment by seronal** [comment]
I believe I have the latest version (v4.13.1), and I am still seeing this issue.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.1


### Stack Trace

Uncaught TypeError: Cannot read property 'setScreenHeightAndWidth' of null

```
At /Users/Serdar/.atom/packages/minimap/lib/minimap-element.coffee:416

TypeError: Cannot read property 'setScreenHeightAndWidth' of null
  at atom-text-editor-minimap.MinimapElement.measureHeightAndWidth (/Users/Serdar/.atom/packages/minimap/lib/minimap-element.coffee:416:5)
  at atom-text-editor-minimap.MinimapElement.pollDOM (/Users/Serdar/.atom/packages/minimap/lib/minimap-element.coffee:386:38)
  at /Users/Serdar/.atom/packages/minimap/lib/minimap-element.coffee:90:52
  at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:217:9)
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:179:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61

```

### Commands

```
     -1:52 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-outlander-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "outlander-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-ternjs, v0.7.1
color-picker, v2.0.11
file-icons, v1.6.7
language-lua, v0.9.4
linter, v1.4.3
linter-jshint, v1.1.5
minimap, v4.13.1
outlander-syntax, v1.0.2
pigments, v0.11.0
save-session, v0.15.7
tool-bar, v0.1.8
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by abe33** [comment]
Ok... please reload Atom, as custom element can't be removed/reloaded you still have the previous version even after an update.

**Comment by LoLei** [comment]
Can confirm that reloading or closing and reopening Atom after updating fixes this issue.

**Comment by abe33** [comment]
Ok, I'm glad to hear that, I'll probably have to take a look at nathansobo/etch to workaround that limitation on custom elements.
