### ISSUE TITLE
Uncaught TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function

### ISSUE THREAD

**Issue by sanguino** [atom-minimap/minimap#405]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.16.0

### Stack Trace

Uncaught TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function

```
At /Users/miguel.sanguino/.atom/packages/minimap/lib/minimap.coffee:200

TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function
  at Minimap.module.exports.Minimap.getTextEditorMaxScrollTop (/Users/miguel.sanguino/.atom/packages/minimap/lib/minimap.coffee:196:3)
  at Minimap.module.exports.Minimap.getTextEditorScrollRatio (/Users/miguel.sanguino/.atom/packages/minimap/lib/minimap.coffee:212:30)
  at Minimap.module.exports.Minimap.getCapedTextEditorScrollRatio (/Users/miguel.sanguino/.atom/packages/minimap/lib/minimap.coffee:217:39)
  at Minimap.module.exports.Minimap.getScrollTop (/Users/miguel.sanguino/.atom/packages/minimap/lib/minimap.coffee:16:3)
  at Minimap.module.exports.Minimap.getLastVisibleScreenRow (/Users/miguel.sanguino/.atom/packages/minimap/lib/minimap.coffee:325:22)
  at Minimap.module.exports.DecorationManagement.emitRangeChanges (/Users/miguel.sanguino/.atom/packages/minimap/lib/mixins/decoration-management.coffee:271:31)
  at Minimap.module.exports.DecorationManagement.emitDecorationChanges (/Users/miguel.sanguino/.atom/packages/minimap/lib/mixins/decoration-management.coffee:263:6)
  at Minimap.module.exports.DecorationManagement.decorateMarker (/Users/miguel.sanguino/.atom/packages/minimap/lib/mixins/decoration-management.coffee:225:6)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.markRange (/Users/miguel.sanguino/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:63:14)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.addDecorations (/Users/miguel.sanguino/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:51:10)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.updateDiffs (/Users/miguel.sanguino/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:42:8)
  at /Users/miguel.sanguino/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1276:25

```

### Commands

```
     -2:47.1.0 core:copy (atom-text-editor.editor.is-focused)
     -2:42.8.0 core:paste (atom-text-editor.editor.is-focused)
     -2:39.5.0 core:cut (atom-text-editor.editor.is-focused)
  2x -2:38.5.0 core:delete (atom-text-editor.editor.is-focused)
     -2:35.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:35.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:34 core:paste (atom-text-editor.editor.is-focused)
     -2:32.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:32.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:23.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:43 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:12.7.0 core:copy (atom-text-editor.editor.is-focused)
     -1:10.7.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:23.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.0 core:copy (atom-text-editor.editor.is-focused)
     -0:02.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "minimap": {
    "plugins": {
      "find-and-replace": true,
      "git-diff": true,
      "selection": true
    }
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
atom-typescript, v7.7.0
emmet, v2.3.13
linter, v1.10.0
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Do you still get this after reloading Atom?

**Comment by anewmanBV** [comment]
I was having the same issue, restarting Atom caused it to go away.

**Comment by cadebward** [comment]
Updating to the latest version and restarting fixed this for me.

**Comment by Kaidjin** [comment]
I still have this error after restarting on Windows.

**Comment by SoullessWaffle** [comment]
I am also on Windows and I do not get this error after updating the package and restarting Atom.
@Kaidjin Did you try updating atom-minimap?

**Comment by Kaidjin** [comment]
@SoullessWaffle You're right, Silly me, I updated atom but not the package. It's gone now, thanks.

**Comment by sanguino** [comment]
Thanks!

It works!

**Comment by ldm314** [comment]
I saw this issue as well and can confirm as well that updating atom-minimap to 4.16.0 fixed it for me.

**Comment by fseminario** [comment]
updating minimap package and restarting fixed it for me

**Comment by slny311** [comment]
Updating and a restart fixed this issue.

**Comment by miclaus** [comment]
uninstalling the minimap package, then reloading from the menu and reinstalling minimap did it for me .

**Comment by cjmabry** [comment]
Issue has been resolved for myself as well after updating package and restarting Atom. Mac OSX 10.11.

**Comment by vingorius** [comment]
after uninstall & install, it was cleared.

**Comment by iCityWork** [comment]
I am getting this error.  Uninstalled and Reinstalled and still getting error.

**Comment by incleaf** [comment]
The error was appeard so I did uninstall and install but it still occur error.
OS X 10.11

**Comment by abe33** [comment]
To all those who still encounter the issue, could you please indicate the version of Atom you're running?

**Comment by incleaf** [comment]
My version is 1.1.0 and also in my windows desktop had same issue but I solved with reinstall

**Comment by abe33** [comment]
Hmm, that's still weird you have to reinstall the package to get the proper udpate. Restarting Atom should be enough.

**Comment by sbecainfo** [comment]
restart solved it but that was weird...

**Comment by death180** [comment]
Updating and restarting Atom worked fine for me on windows.

**Comment by incleaf** [comment]
uninstall -> install -> restart atom
it's work now

**Comment by marcofloriano** [comment]
Same error, still getting after restart.

**Comment by abe33** [comment]
To all the people that still get the error after a restart: are you sure to run the latest version (v4.16)?

**Comment by lengziyu** [comment]
I was having the same issue

**Comment by jpaulin** [comment]
Here's a noodie (it was supposed to be n00bie, but even got that pre-first-coffee-cup typo included). 
Noodie's questions and remarks: 
1. Wonderful to see the reporting! I love this kind of immediate action upon bugs. I too have the same exact message.
2. Didn't notice the update in Atom. Now checking that option... done. Updated to 4.16.0 
3. My question actually is: are all/some/none of Atom packages "hot-updateable", ie. they would be in effect immediately after updating - even without restarting Atom ?

Cheers! -> getting cup of coffee ;-)

**Comment by abe33** [comment]
> My question actually is: are all/some/none of Atom packages "hot-updateable", ie. they would be in effect immediately after updating - even without restarting Atom ?

In theory, every package is hot-updateable, in practice, though, there's still some situations that aren't well supported by Atom. I've encountered at least two with the minimap (and other packages I maintain): 

1. The package uses custom elements, and an update contains a change in a custom element related to a change in an API. Once registered a custom element cannot be unregistered, so after the update Atom is still running the old version. Which can lead to some weird issues.
2. The package declare a new version for one of its dependencies. In that case, even if the new version was properly installed it could happen that Atom doesn't reload the new version, leading again to some weird and unpredictable issues.

In the problem at hand, the main issue is that I was relying on some private API that was removed without going though a deprecation notice phase. In that case, people who update Atom without updating the packages before restarting Atom will get this kind of error (the old API no longer exists but the package still expect it to exist)

**Comment by davidrpoliti** [comment]
Still seeing this in 1.1.0 Mac 10.10.5

**Comment by misterzik** [comment]
Mac El Capitan for me works like this, 

Open Atom -> Press `CMD(Apple) + ,(Comma)` to open up Atom Settings, Then go to Updates section, Click `Check for updates`, wait a minute for data to load, Then Click `Update All`. 

Go make coffee :coffee:

Restart your program and there you have it!

**Comment by maxatbrs** [comment]
Can confirm - update package, restart. Bingo bango.

Yosemite 10.10.2 with Atom 1.1.0

**Comment by LorinRicker** [comment]
Saw this starting with Atom 1.1.0, updating atom-minimap to 4.16.0, then restarting Atom, fixed it for me.

**Comment by simonguo** [comment]
updating minimap to 4.16.0

**Comment by appstore73** [comment]
apm install minimap

**Comment by aphexddb** [comment]
confirmed that `apm install minimap` solved this error

**Comment by clongbupt** [comment]
```bash
$ apm install minimap
Installing minimap to /Users/changlong.wu/.atom/packages ✓
```

Already installed, but still reported this kind of exception.

**Comment by becauseinterwebs** [comment]
apm install minimap

Fixed it for me. Atom v1.2.3 on Mac OSX 10.9.5

**Comment by abe33** [comment]
Do you think I can close the issue, or are there still issues for someone?

**Comment by fangmobile** [comment]
apm install minimap

Fixed it for me. Atom v1.2.3 on Mac OSX 10.11.1

**Comment by meilinger** [comment]
`apm install minimap` also fixed it for me on OSX 10.11.1 - Atom v1.2.3

**Comment by anasbayu** [comment]
update the package and restart Atom. Voila

**Comment by Karla-Isabel-Sandoval** [comment]
Running  'apm install minimap' also solved the minimap bug for me on OS X 10.11 El Capitan.
After I restarted Atom and that cleared the bug.

**Comment by ddawkins7** [comment]
Updated the mini-map to current version and restarted worked for me also. (OS X - Yosemite)

**Comment by adammendoza** [comment]
I'm still having this issue after the latest update.

**Comment by sanguino** [comment]
Did you restart? It works for me

Enviado desde mi iPhone

**Comment by adammendoza** [comment]
haha, I've restarted many a times my friend, to no avail :(.

**Comment by sanguino** [comment]
So sorry, restart works for me... Could you try to remove and install again? 

Enviado desde mi iPhone

**Comment by abe33** [comment]
@adammendoza Which version of Atom are you running?

**Comment by adammendoza** [comment]
Version 1.7.4. I have automatic updates on but maybe not the latest version.

**Comment by abe33** [comment]
Ok, because the original issue was for 1.1 and since the Atom API changed quite a lot since then I think the stack trace must be quite different, if you could provide me with it it would be great!

**Comment by adammendoza** [comment]
There your go. Apparently it needs coffee. thx

I'm running version 1.8.0

Uncaught TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function
/Users/adam/.atom/packages/minimap/lib/minimap.coffee:142
Hide Stack Trace
TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function
    at Minimap.module.exports.Minimap.getTextEditorMaxScrollTop (/Users/adam/.atom/packages/minimap/lib/minimap.coffee:142:52)
    at Minimap.module.exports.Minimap.getTextEditorScrollRatio (/Users/adam/.atom/packages/minimap/lib/minimap.coffee:151:53)
    at Minimap.module.exports.Minimap.getCapedTextEditorScrollRatio (/Users/adam/.atom/packages/minimap/lib/minimap.coffee:155:31)
    at Minimap.module.exports.Minimap.getScrollTop (/Users/adam/.atom/packages/minimap/lib/minimap.coffee:199:28)
    at atom-text-editor-minimap.MinimapElement.update (/Users/adam/.atom/packages/minimap/lib/minimap-element.coffee:361:83)
    at /Users/adam/.atom/packages/minimap/lib/minimap-element.coffee:338:17
The error was thrown from the minimap package. This issue has already been reported.

**Comment by abe33** [comment]
@adammendoza Hmm, I think there's something wrong with your minimap install, because it no longer uses coffeescript since v4.17.0, so you might be running an old version (more than 6 months) that is no longer compatible with the current Atom API.
