### ISSUE TITLE
Uncaught TypeError: atom.views.pollDocument is not a function

### ISSUE THREAD

**Issue by CapnSquirrel** [atom-minimap/minimap#625]
[Enter steps to reproduce:]

1. open file
2. this triggers the bug

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.3

### Stack Trace

Uncaught TypeError: atom.views.pollDocument is not a function

```
At C:\Users\Alejandro\.atom\packages\minimap\lib\minimap-element.js:345

TypeError: atom.views.pollDocument is not a function
    at HTMLElement.attachedCallback (/packages/minimap/lib/minimap-element.js:345:39)
    at /packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:15:57)
    at HTMLElement.PaneElement.activeItemChanged (D:/atom/app-1.19.0/resources/app/src/pane-element.js:144:24)
    at Function.module.exports.Emitter.simpleDispatch (D:/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.setActiveItem (D:/atom/app-1.19.0/resources/app/src/pane.js:337:28)
    at Pane.module.exports.Pane.activateItemAtIndex (D:/atom/app-1.19.0/resources/app/src/pane.js:475:25)
    at Pane.module.exports.Pane.activatePreviousItem (D:/atom/app-1.19.0/resources/app/src/pane.js:440:27)
    at Pane.module.exports.Pane.removeItem (D:/atom/app-1.19.0/resources/app/src/pane.js:630:22)
    at Pane.module.exports.Pane.destroyItem (D:/atom/app-1.19.0/resources/app/src/pane.js:706:22)
    at Pane.module.exports.Pane.addItem (D:/atom/app-1.19.0/resources/app/src/pane.js:557:20)
    at Pane.module.exports.Pane.activateItem (D:/atom/app-1.19.0/resources/app/src/pane.js:489:20)
    at Workspace.<anonymous> (D:/atom/app-1.19.0/resources/app/src/workspace.js:1161:20)
    at Generator.next (<anonymous>)
    at step (D:/atom/app-1.19.0/resources/app/src/workspace.js:11:279)
```

### Commands

```
     -3:52.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
docblockr 0.9.4 
linter 1.11.23 
linter-javac 1.9.4 
minimap 4.29.3 
platformio-ide-terminal 2.2.3 
project-manager 3.3.3 
seti-syntax 1.1.2 
seti-ui 1.6.1 
```

**Comment by joedots1** [comment]
I see this is closed now, what's the resolution?

**Comment by CapnSquirrel** [comment]
This was closed without resolution, still trying to solve it.

**Comment by afghl** [comment]
Hi, @joedots1 , @CapnSquirrel , I updated minimap to latest version and it was fixed.

**Comment by liuqipeng417** [comment]
Hi，everyone，this problem is still in my atom. 
minimap version: 4.29.6
OS: win 10
atom version: 1.19.0 ia32

**Comment by cruzenaldo** [comment]
Just update the packages and work like a charm, thq @afghl

**Comment by ummahusla** [comment]
I have the latest version but this problem still exists for me. Atom 1.19

**Comment by sn34ks** [comment]
You may have some packages that need updating:

Packages-> Settings View-> Update Atom Packages-> Update Packages Themes

**Comment by alfonsotech** [comment]
Updating the minimap package also worked for me - thanks!

**Comment by kinduff** [comment]
Confirmed that updating fixes the exception.

**Comment by nvien** [comment]
Updating helped!

**Comment by OneStig** [comment]
Thank you for fixing. I had to deal with this bug too.
