### ISSUE TITLE
Uncaught TypeError: atom.views.pollDocument is not a function

### ISSUE THREAD

**Issue by dmalik** [atom-minimap/minimap#632]
[Enter steps to reproduce:]

1. Install package

**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.29.6

### Stack Trace

Uncaught TypeError: atom.views.pollDocument is not a function

```
At /Users/dmalik/.atom/packages/minimap/lib/minimap-element.js:345

TypeError: atom.views.pollDocument is not a function
    at HTMLElement.attachedCallback (/packages/minimap/lib/minimap-element.js:345:39)
    at /packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:15:57)
    at HTMLElement.attach (/packages/minimap/lib/minimap-element.js:414:15)
    at subscriptions.add.atom.workspace.observeTextEditors (/packages/minimap/lib/main.js:394:22)
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:717:15)
    at Main.initSubscriptions (/packages/minimap/lib/main.js:388:43)
    at Main.toggle (/packages/minimap/lib/main.js:184:12)
    at Main.activate (/packages/minimap/lib/main.js:115:55)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -2:34.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-gooey-syntax 0.2.1 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
autoclose-html 0.23.0 
base16-ocean-dark-spacegray 0.13.0 
beacon-ui 0.5.0 
chester-atom-syntax 0.1.1 
file-icons 2.0.16 
fonts 2.0.0 
git-control 0.8.2 
git-plus 7.3.3 
language-babel 2.55.6 
linter 1.11.23 
linter-eslint 8.1.2 
markdown-preview-plus 2.4.8 
markdown-writer 2.6.4 
meteor-api 2.20.0 
minimap 4.29.6 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.1 
platformio-ide-terminal 2.6.0 
seti-icons 1.3.4 
seti-syntax 1.1.2 
seti-ui 1.6.1 
sort-lines 0.14.0 
webbox-color 0.5.9 
```

**Comment by kodescience** [comment]
Update your minimap package.

**Comment by kamalkech** [comment]
I have same issue, can u explain more how to fixe it ?

**Comment by DanielAlcorn** [comment]
Yep this is a very irritating problem

**Comment by mehcode** [comment]
This should have been fixed. I'm looking in the source and it should definitely not be triggering this bug. Can you update to `v4.29.7` and let me know if this happens again?

**Comment by Furchin** [comment]
I am on 4.29.7 and see the issue still.
![screenshot 2017-09-19 15 22 03](https://user-images.githubusercontent.com/1891931/30618217-53989a22-9d4e-11e7-8181-a8f47197d868.png)

**Comment by maviday** [comment]
Same issue today.

**Comment by bboynton97** [comment]
I'm getting that issue too

**Comment by jlmoody** [comment]
+1

**Comment by chcculle** [comment]
I have the same issue.  very annoying.

**Comment by Geokafas** [comment]
go to setting/packages find the minimap package and update it. It fixed the problem for me.

**Comment by kamalkech** [comment]
@Geokafas : i have minimap package already updated but probleme still

**Comment by Geokafas** [comment]
@kamalkech Then i can't help you. Try reinstalling the hole thing

**Comment by chcculle** [comment]
thanks upgrade fixed it.

**Comment by Newbie66** [comment]
Thanks! - reinstall fix it.

**Comment by theyapps** [comment]
I reinstalled minimap and still see the same issue.

**Comment by kamalkech** [comment]
@theyapps : when you reinstall or update atom, then update the package too minimap

**Comment by GabiArzu** [comment]
I still got that problem, even after i reinstalled atom and minimap

**Comment by sebastianfromearth** [comment]
upgrade fixed it for me :)

**Comment by edgarZM** [comment]
I re install minimap and update the other packages and solved

**Comment by JuanM04** [comment]
I've tried reinstalling atom and minimap but it doesn't work.

**Comment by labsolsat** [comment]
update all packages and remove the minimap error, now it works without problems

**Comment by theyapps** [comment]
I gave up on having the mini map and eventually an update center that fixed it. Not sure which one.

**Comment by ngapeakame** [comment]
Just go to settings and update it, all solved. Thanks

**Comment by Shrizt** [comment]
updated to 4.29.8 - issue persists :(
any workaround? clearing some cache?

**Comment by CaesarChoperena** [comment]
Updated all packeges it worked, try it.

**Comment by Shrizt** [comment]
hi, yep, after updated all packages - it works, thanks. I think the issue may be closed.

**Comment by mafonya** [comment]
Happened to me today. Updating all packages helped.

**Comment by aminya** [comment]
I am closing this. Updating all the packages and restarting Atom fixes this.
